import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { QueryProvider } from "./query-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable}>
      <body style={{ background: "#f4ecd8", color: "#3b2f1c", fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace' }}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
